##### Practica de un dataset de kfc

### Importamos las librerias necesarias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Tenemos que leer y analizar el dataset

In [2]:
df = pd.read_csv('dataset/KFC_Past_Sales_Dataset.csv')

In [3]:
df.head()

   Year Month    Country  Branch_ID   Sales  Customers  Marketing_Spend
0  2022   Aug         UK  KFC_UK_01  206611       4568            23891
1  2018   May      India  KFC_IN_01   69645       1715             6190
2  2020   Nov         UK  KFC_UK_01  170226       4672             6706
3  2024   Dec  Australia  KFC_AU_01   90483       2363            17230
4  2019   Nov         UK  KFC_UK_01   94260       2207            28050

In [ ]:
df.columns

Index(['Year', 'Month', 'Country', 'Branch_ID', 'Sales', 'Customers',
       'Marketing_Spend'],
      dtype='str')

In [8]:
df.shape

(8000, 7)

In [9]:
print(df.columns.tolist())
print(df.dtypes)
df.head()

['Year', 'Month', 'Country', 'Branch_ID', 'Sales', 'Customers', 'Marketing_Spend']
Year               int64
Month                str
Country              str
Branch_ID            str
Sales              int64
Customers          int64
Marketing_Spend    int64
dtype: object

   Year Month    Country  Branch_ID   Sales  Customers  Marketing_Spend
0  2022   Aug         UK  KFC_UK_01  206611       4568            23891
1  2018   May      India  KFC_IN_01   69645       1715             6190
2  2020   Nov         UK  KFC_UK_01  170226       4672             6706
3  2024   Dec  Australia  KFC_AU_01   90483       2363            17230
4  2019   Nov         UK  KFC_UK_01   94260       2207            28050

### Ver informacion completa del dataset

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             8000 non-null   int64
 1   Month            8000 non-null   str
 2   Country          8000 non-null   str
 3   Branch_ID        8000 non-null   str
 4   Sales            8000 non-null   int64
 5   Customers        8000 non-null   int64
 6   Marketing_Spend  8000 non-null   int64
dtypes: int64(4), str(3)
memory usage: 437.6 KB

## Hacemos una limpieza de los datos

### Ver los valores nulos

In [11]:
df.isnull().sum()

Year               0
Month              0
Country            0
Branch_ID          0
Sales              0
Customers          0
Marketing_Spend    0
dtype: int64

### Ver los valores duplicados

In [12]:
df.duplicated().sum()

np.int64(0)


### Ver los paises

In [13]:
df['Country'].unique()

<StringArray>
['UK', 'India', 'Australia', 'USA', 'Canada']
Length: 5, dtype: str

### Ver cuantas sucursales unicas hay

In [14]:
df['Branch_ID'].nunique()

13

### Ordenamos el tiempo por orden logico

In [15]:
month_order = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
df['Month'] = pd.Categorical(df['Month'], categories=month_order, ordered=True)

### Analizar las variables por grupos

In [16]:
df.groupby('Country')['Sales'].sum().sort_values(ascending=False)

Country
Canada       247338572
UK           243262528
India        238217516
Australia    235368001
USA          226516412
Name: Sales, dtype: int64

In [21]:
df.groupby('Year')['Sales'].sum()

Year
2018    168697492
2019    170833341
2020    170540121
2021    170897519
2022    169806190
2023    164978857
2024    174949509
Name: Sales, dtype: int64

In [22]:
df[['Marketing_Spend', 'Sales']].corr()

                 Marketing_Spend     Sales
Marketing_Spend         1.000000  0.152775
Sales                   0.152775  1.000000

In [23]:
df.groupby('Month')['Sales'].mean()

Month
Jan    148962.796512
Feb    150396.997203
Mar    147441.609720
Apr    149571.373372
May    152051.840237
Jun    149114.968703
Jul    149956.385093
Aug    148192.309707
Sep    150238.642136
Oct    145697.825949
Nov    145809.850769
Dec    148123.174837
Name: Sales, dtype: float64

In [26]:
# Ventas por cliente
df['Sales_per_Customer'] = df['Sales'] / df['Customers']
df.groupby('Country')['Sales_per_Customer'].mean().sort_values(ascending=False)

Country
UK           40.610855
Australia    40.593117
Canada       40.581977
USA          40.565996
India        40.450860
Name: Sales_per_Customer, dtype: float64